// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjERM1hPNuBb8AEBZVWZZiKjhj3ooHqU',
    appId: '1:441347250440:android:74fee86a6fa2f448afb4bd',
    messagingSenderId: '441347250440',
    projectId: 'mynotes-5d255',
    storageBucket: 'mynotes-5d255.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgq7n26QacByyJgbdCZT5p9RVYi8y_llw',
    appId: '1:441347250440:web:262b90ebdb2b7e7bafb4bd',
    messagingSenderId: '441347250440',
    projectId: 'mynotes-5d255',
    authDomain: 'mynotes-5d255.firebaseapp.com',
    storageBucket: 'mynotes-5d255.appspot.com',
    measurementId: 'G-NGPW8CNTJ3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmIIM2vjBkq2TWBHYjWZuGBbDNkyp0P2o',
    appId: '1:441347250440:ios:0533aba8fa71ecefafb4bd',
    messagingSenderId: '441347250440',
    projectId: 'mynotes-5d255',
    storageBucket: 'mynotes-5d255.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmIIM2vjBkq2TWBHYjWZuGBbDNkyp0P2o',
    appId: '1:441347250440:ios:0533aba8fa71ecefafb4bd',
    messagingSenderId: '441347250440',
    projectId: 'mynotes-5d255',
    storageBucket: 'mynotes-5d255.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgq7n26QacByyJgbdCZT5p9RVYi8y_llw',
    appId: '1:441347250440:web:088ea5e369d98b7fafb4bd',
    messagingSenderId: '441347250440',
    projectId: 'mynotes-5d255',
    authDomain: 'mynotes-5d255.firebaseapp.com',
    storageBucket: 'mynotes-5d255.appspot.com',
    measurementId: 'G-FPHVW0Q5QW',
  );

}